version: "3.7"

services:
  bbyen:
    image: marcelrobitaille/bbyen:2.0.1
    container_name: bbyen
    volumes:
      - ./config.json:/usr/src/app/config.json
      - ./google-credentials.json:/usr/src/app/google-credentials.json
      - ./.google-auth-token.json:/usr/src/app/.google-auth-token.json
      - ./database.sqlite:/usr/src/app/database.sqlite
    ports:
      - 3050:3050
    restart: unless-stopped
