name: Publish Docker images
on: push
jobs:
  build-container:
    name: Build Docker container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Publish to GitHub Packages
        uses: docker/build-push-action@v3
        with:
          # username: ${{ github.actor }}
          # password: ${{ secrets.GITHUB_TOKEN }}
          # registry: docker.pkg.github.com
          # repository: ${{ github.repository }}/bbyen
          tags: MarcelRobitaille/bbyen:latest
          push: true
      # - name: Publish to Docker Hub
      #   uses: docker/build-push-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      #     repository: MarcelRobitaille/bbyen
      #     tags: latest
